language: cpp

jobs:
  include:
    - os: osx
      compiler: gcc
      osx_image: xcode11.2
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
	    - cmake
	    - cmake-data
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons: { apt: { packages: ['doxygen'] } }


before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -D ENABLE_TESTS:BOOL=TRUE .
  - cmake --build . -- -j2
  - ctest -j2
