language: cpp

jobs:
  include:
#    - os: osx
#      compiler: gcc
#      osx_image: xcode11.2
#      env:
#        - GCC_VER="9"
#        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
#      addons:
#        homebrew:
#          packages:
#          - cppunit
#          - mruby

    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
            - cmake
            - cmake-data
            - mruby
            - libmruby-dev
            - libcppunit-dev

    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
            - cmake
            - cmake-data
            - mruby
            - libmruby-dev
            - libcppunit-dev

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:/usr/local/Cellar/cppunit/1.15.1/lib"
  - cmake -D ENABLE_TESTS:BOOL=TRUE .
  - cmake --build . -- -j2
  - ctest -j2
